require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/claims", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Claim. As you add validations to Claim, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Claim.create! valid_attributes
      get claims_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      claim = Claim.create! valid_attributes
      get claim_url(claim)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_claim_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      claim = Claim.create! valid_attributes
      get edit_claim_url(claim)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Claim" do
        expect {
          post claims_url, params: { claim: valid_attributes }
        }.to change(Claim, :count).by(1)
      end

      it "redirects to the created claim" do
        post claims_url, params: { claim: valid_attributes }
        expect(response).to redirect_to(claim_url(Claim.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Claim" do
        expect {
          post claims_url, params: { claim: invalid_attributes }
        }.to change(Claim, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post claims_url, params: { claim: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested claim" do
        claim = Claim.create! valid_attributes
        patch claim_url(claim), params: { claim: new_attributes }
        claim.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the claim" do
        claim = Claim.create! valid_attributes
        patch claim_url(claim), params: { claim: new_attributes }
        claim.reload
        expect(response).to redirect_to(claim_url(claim))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        claim = Claim.create! valid_attributes
        patch claim_url(claim), params: { claim: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested claim" do
      claim = Claim.create! valid_attributes
      expect {
        delete claim_url(claim)
      }.to change(Claim, :count).by(-1)
    end

    it "redirects to the claims list" do
      claim = Claim.create! valid_attributes
      delete claim_url(claim)
      expect(response).to redirect_to(claims_url)
    end
  end
end
